### ISSUE TITLE
alr codes for getting access to song streams

### ISSUE THREAD

**Issue by Tomato6966** [kaogurai/lavalink-plugin#1]
you can login with email & password --> f12 --> applications --> cookies get arl code

(just let the user add alr to application.yml)
(idk maybe it updates. so you might need to just request cookies every 1 hr and then user needs to provide email & password, or maybe cookie is enough but that could be for future things)

this would allow direct song playing from deezer!

with that you can download a deezer stream on 128kbps (for everything) and if your account is premium even higher bitrates!! (320 or even the 1240kbps HIFI Audio)

Check out the python project

```
pip deemix
```

which works very well with that!

**Comment by ryan5453** [comment]
No
